JigitalShop/JigitalShop/urls.py
from django.contrib import admin
from django.urls import path

import MainPage.views as main_views
import Store.views as store_views

app_name = 'store'

urlpatterns = [
    path('admin/', admin.site.urls , name='admin'),
    path('', main_views.main_page_view, name='main_page_view'),
    path('store', store_views.store_page, name='store'),
    path('editstore', store_views.admin_store, name='edit_store'),

    path('add/', store_views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', store_views.edit_product, name='edit_product'),

    path('delete/<int:pk>/', store_views.delete_product, name='delete_item'),
    path('product/<int:id>/', store_views.product_detail, name='product_detail'),
]

JigitalShop/MainPage/models.py
from django.db import models

# Create your models here.

JigitalShop/Store/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Ціна")
    description = models.TextField(verbose_name="Опис")
    manufacturer = models.CharField(max_length=100, verbose_name="Виробник")
    rate = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        validators=[MinValueValidator(1.0),  MaxValueValidator(5.0)], default=5.0,
        verbose_name="Рейтинг"
    )
    photo = models.ImageField(upload_to='photos', verbose_name="Фото")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE, verbose_name="Товар")
    text = models.TextField(verbose_name="Текст відгуку")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")

    def __str__(self):
        return f"Відгук на {self.product.name}"

JigitalShop/MainPage/views.py
from django.shortcuts import render



# Create your views here.
def main_page_view(request):
    context = {
    }
    return render(request, "mainpage.html", context)

JigitalShop/Store/views.py
from django.shortcuts import render,get_object_or_404, redirect
from Store.models import Product
from Store.form import ProductForm, ReviewForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def store_page(request):
    items = Product.objects.all()
    return render(request, 'main_store.html', {'items': items})

def admin_store(request):
    items = Product.objects.all()
    return render(request, 'edit_store.html', {'items': items})

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('edit_store')
    else:
        form = ProductForm()
    return render(request, 'add_product.html', {'form': form})

def edit_product(request, pk):
    product = get_object_or_404(Product, id=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('edit_store')
    else:
        form = ProductForm(instance=product)
    return render(request, 'edit_product.html', {'form': form, 'product': product})

def delete_product(request,pk ):
    try:
        product = get_object_or_404(Product, id=pk)
        product.delete()
        messages.success(request, 'Продукт успішно видалено!')
    except Exception as e:
        print(e)
        messages.error(request, f'Помилка при видаленні товару: {str(e)}')
    return redirect('edit_store')

def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    reviews = product.reviews.all()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.save()
            return redirect('product_detail', id=product.id)
    else:
        form = ReviewForm()
    return render(request, 'product_details.html', {'product': product, 'reviews': reviews, 'form': form})

# def edit_product(request, id):
#     product = get_object_or_404(Product, id=id)
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             return redirect('store:product_details', id=id)
#     else:
#         form = ProductForm(instance=product)
#     return render(request, 'edit_product.html', {'form': form})

# def delete_product.js(request, id):
#     product = get_object_or_404(Product, id=id)
#     if request.method == 'POST':
#         product.delete()
#         return redirect('store:main_page_view')
#     return render(request, 'delete_product.js.html', {'product': product})

JigitalShop/JigitalShop/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block headcode %}
    {% endblock %}
    <title>
        {% block title %}{% endblock %}
    </title>

</head>
<body>
<header>
    <img src="{% static 'images/logo.png' %}" alt="home" id="homeimg">
    <nav>
        <ul class="nav-links">
            <li><a href="{% url 'store' %}">Store</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">Top-100</a></li>
            <li><a href="{% url 'edit_store' %}">Edit Store</a></li>
        </ul>
    </nav>
    <div class="extra-button">☰</div>
</header>
{% block content %}
{% endblock %}
</body>
</html>

JigitalShop/MainPage/templates/mainpage.html
{% extends "main/layout.html" %}

{% block headcode %}
    {% load static %}
{% endblock %}


{% block content %}
    {% load static %}
{% endblock %}

JigitalShop/Store/templates/add_product.html
{% extends 'main/layout.html' %}
{% load static %}

{% block headcode %}
    <link rel="stylesheet" href="{% static 'css/add_product.css' %}">
    <link rel="icon" href="{% static 'images/plus.png' %}" type="image/x-icon">
{% endblock %}


{% block content %}
    <div class="container mt-5">
        <h2>Додати продукт</h2>
        <form method="post" enctype="multipart/form-data" class="add-product-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Назва продукту</label>
                <input type="text" id="id_name" name="name" class="form-control" placeholder="Введіть назву продукту">
            </div>
            <div class="form-group">
                <label for="id_price">Ціна</label>
                <input type="number" step="0.01" id="id_price" name="price" class="form-control"
                       placeholder="Введіть ціну (грн)">
            </div>
            <div class="form-group">
                <label for="id_rate">Рейтинг (1.0 - 5.0)</label>
                <input type="number" step="0.1" id="id_rate" name="rate" class="form-control"
                       placeholder="Введіть рейтинг продукту">
            </div>
            <div class="form-group">
                <label for="id_manufacturer">Виробник</label>
                <input type="text" id="id_manufacturer" name="manufacturer" class="form-control"
                       placeholder="Введіть назву виробника">
            </div>
            <div class="form-group">
                <label for="id_photo">Фото</label>
                <input type="file" id="id_photo" name="photo" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_description">Опис</label>
                <textarea id="id_description" name="description" class="form-control"
                          placeholder="Введіть опис продукту"></textarea>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Додати</button>
            </div>
        </form>
    </div>
{% endblock %}

JigitalShop/Store/templates/edit_product.html
{% extends 'main/layout.html' %}
{% load static %}

{% block headcode %}
    <link rel="stylesheet" href="{% static 'css/add_product.css' %}">
    <link rel="icon" href="{% static 'images/plus.png' %}" type="image/x-icon">
    <script src="{% static 'js/add_product.js' %}" defer></script>
{% endblock %}


{% block content %}
    <div class="container mt-5">
        <h2>Змінити продукт</h2>
        <form method="post" enctype="multipart/form-data" class="add-product-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Назва продукту</label>
                <input type="text" id="id_name" name="name" class="form-control" placeholder="Введіть назву продукту">
            </div>
            <div class="form-group">
                <label for="id_price">Ціна</label>
                <input type="number" step="0.01" id="id_price" name="price" class="form-control"
                       placeholder="Введіть ціну (грн)">
            </div>
            <div class="form-group">
                <label for="id_rate">Рейтинг (1.0 - 5.0)</label>
                <input type="number" step="0.1" id="id_rate" name="rate" class="form-control"
                       placeholder="Введіть рейтинг продукту">
            </div>
            <div class="form-group">
                <label for="id_manufacturer">Виробник</label>
                <input type="text" id="id_manufacturer" name="manufacturer" class="form-control"
                       placeholder="Введіть назву виробника">
            </div>
            <div class="form-group">
                <label for="id_photo">Фото</label>
                <input type="file" id="id_photo" name="photo" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_description">Опис</label>
                <textarea id="id_description" name="description" class="form-control"
                          placeholder="Введіть опис продукту"></textarea>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Змінити</button>
            </div>
        </form>
    </div>
{% endblock %}

JigitalShop/Store/templates/edit_store.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Edit store{% endblock %}

{% block headcode %}
    <link rel="stylesheet" href="{% static 'css/edit_store.css' %}">
    <link rel="icon" href="{% static 'images/gear.png' %}" type="image/x-icon">
{% endblock %}

{% block content %}
            <nav class="store_van">
            <a href="{% url 'add_product' %}" style="margin: 20px; display: inline-block;">
                <h1>Додати продукт +</h1>
            </a>
        </nav>
    <div class="store_plate">
        <div class="item_list">
            {% for item in items %}
                <div class="item_product">
                    <img
                            class="product_img"
                            src="{{ item.photo }}"
                            alt="{{ item.name }}"
                            onerror="this.onerror=null; this.src='{% static 'images/noimages.png' %}';">
                    <div class="product_info">
                        <h1 class="product_name">{{ item.name }}</h1>
                        <h1 class="product_description">{{ item.price }} грн</h1>
                        <h1 class="product_description">Рейтинг: {{ item.rate }}</h1>
                    </div>
                    <div>
                        <a class="item_btn edit_btn" data-id="{{ item.id }}" href="{% url 'edit_product' item.id %}">
                            <img src="{% static 'images/gear.png' %}" alt="Description">
                        </a>
                        <a class="item_btn delete_btn" data-id="{{ item.id }}" href="{% url 'delete_item' item.id %}">
                            <img  src="{% static 'images/trash.png' %}" alt="Description">
                        </a>
                    </div>
                </div>
            {% empty %}
                <p>Немає доступних продуктів.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

JigitalShop/Store/templates/main_store.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Store{% endblock %}

{% block headcode %}
    <link rel="stylesheet" href="{% static 'css/product_list.css' %}">
    <link rel="icon" href="{% static 'images/basket.png' %}" type="image/x-icon">
{% endblock %}

{% block content %}
<div class="store_plate">
        <div class="item_list">
            {% for item in items %}
                <div class="item_product">
                    <img
                            class="product_img"
                            src="{{ item.photo }}"
                            alt="{{ item.name }}"
                            onerror="this.onerror=null; this.src='{% static 'images/noimages.png' %}';">
                    <div class="product_info">
                        <h1 class="product_name">{{ item.name }}</h1>
                        <h1 class="product_description">{{ item.price }} грн</h1>
                        <h1 class="product_description">Рейтинг: {{ item.rate }}</h1>
                    </div>
                    <div class="item_btn">
                        <a class="item_detail_btn" href="{% url 'product_detail' item.id %}">Детальніше</a>
                    </div>
                </div>
            {% empty %}
                <p>Немає доступних продуктів.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

JigitalShop/Store/templates/product_details.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Details{% endblock %}

{% block headcode %}
    <link rel="stylesheet" href="{% static 'css/product_details.css' %}">
    <link rel="icon" href="{% static 'images/gear.png' %}" type="image/x-icon">
{% endblock %}

{% block content %}
<div class="product-card">
    <div class="product-image">
        <img
                            class="product_img"
                            src="{{ item.photo }}"
                            alt="{{ item.name }}"
                            onerror="this.onerror=null; this.src='{% static 'images/noimages.png' %}';">
    </div>
    <div class="product-details">
        <h1 class="product-title">{{ product.name }}</h1>
        <h2 class="product-price">{{ product.price }} грн</h2>
        <h3 class="product-rating">Рейтинг: {{ product.rate }}</h3>
        <p class="product-description">{{ product.description }}</p>
        <p class="product-manufacturer">Виробник: {{ product.manufacturer }}</p>
    </div>
    <div class="btn">
        <a class="btn_back" href="{% url 'store' %}">←</a>
    </div>
</div>

{% endblock %}